#!/usr/bin/env python

from selene_sdk.utils import load_path
from selene_sdk.utils import parse_configs_and_run

import hdf5_sampler

configs = load_path("model.yml", instantiate=False)
parse_configs_and_run(configs, lr=0.001)
